/** Static fallback when API has no global presence data */

export const STATIC_GLOBAL_PRESENCE = [
  {
    slug: 'uae',
    title: 'United Arab Emirates',
    subtitle: 'Dubai & Abu Dhabi export hub',
    type: 'country',
    clientSegment: 'Middle East',
    countryCode: 'AE',
    coordinates: [54.3773, 24.4539],
    summary: 'Long-standing supply of loading arms, swivel joints, and seal support systems to terminals and EPC partners across the UAE.',
    highlights: ['Terminal & depot equipment', 'EPC and trading partners', 'After-sales technical support'],
    projects: [
      { title: 'Top loading arm packages', summary: 'Supplied engineered arms for petroleum terminals.', status: 'Delivered' },
    ],
    sortOrder: 1,
  },
  {
    slug: 'saudi-arabia',
    title: 'Saudi Arabia',
    clientSegment: 'Middle East',
    coordinates: [45.0792, 23.8859],
    summary: 'Engineering and fabrication support for marine and oilfield service companies in KSA.',
    highlights: ['Marine service integration', 'Loading & unloading systems'],
    projects: [],
    sortOrder: 2,
  },
  {
    slug: 'kuwait',
    title: 'Kuwait',
    clientSegment: 'Middle East',
    coordinates: [47.4818, 29.3117],
    summary: 'Trading and project supply for fluid handling equipment in Kuwait.',
    highlights: ['Trading partner network'],
    projects: [],
    sortOrder: 3,
  },
  {
    slug: 'qatar',
    title: 'Qatar',
    clientSegment: 'Middle East',
    coordinates: [51.1839, 25.3548],
    summary: 'Supplies to Doha-based project and procurement organizations.',
    highlights: ['Project supplies'],
    projects: [],
    sortOrder: 4,
  },
  {
    slug: 'nigeria',
    title: 'Nigeria',
    clientSegment: 'Africa',
    coordinates: [8.6753, 9.082],
    summary: 'Bulk storage and petroleum logistics clients across West Africa.',
    highlights: ['Bulk storage terminals'],
    projects: [],
    sortOrder: 5,
  },
  {
    slug: 'ghana',
    title: 'Ghana',
    clientSegment: 'Africa',
    coordinates: [-1.0232, 7.9465],
    summary: 'Export partnerships supporting petroleum and industrial infrastructure in Ghana.',
    highlights: ['Regional distribution'],
    projects: [],
    sortOrder: 6,
  },
  {
    slug: 'egypt',
    title: 'Egypt',
    clientSegment: 'Africa',
    coordinates: [30.8025, 26.8206],
    summary: 'Fertilizer and energy sector clients in Egypt.',
    highlights: ['Process industry supply'],
    projects: [],
    sortOrder: 7,
  },
  {
    slug: 'indonesia',
    title: 'Indonesia',
    clientSegment: 'Europe & Others',
    coordinates: [113.9213, -0.7893],
    summary: 'Multiple Indonesian trading and engineering partners for SEPL products.',
    highlights: ['Southeast Asia hub'],
    projects: [],
    sortOrder: 8,
  },
  {
    slug: 'bangladesh',
    title: 'Bangladesh',
    clientSegment: 'Europe & Others',
    coordinates: [90.3563, 23.685],
    summary: 'Engineering contractors and industrial buyers in Bangladesh.',
    highlights: ['Infrastructure projects'],
    projects: [],
    sortOrder: 9,
  },
  {
    slug: 'greece',
    title: 'Greece',
    clientSegment: 'Europe & Others',
    coordinates: [21.8243, 39.0742],
    summary: 'European process equipment integration through Greek partners.',
    highlights: ['EU-adjacent supply'],
    projects: [],
    sortOrder: 10,
  },
  {
    slug: 'usa',
    title: 'United States',
    subtitle: 'California & North America',
    clientSegment: 'Europe & Others',
    coordinates: [-119.4179, 36.7783],
    summary: 'Engineered systems export to North American integrators.',
    highlights: ['North America exports'],
    projects: [],
    sortOrder: 11,
  },
  {
    slug: 'iran',
    title: 'Iran',
    clientSegment: 'Europe & Others',
    coordinates: [53.688, 32.4279],
    summary: 'Engineering supply relationships in the Iranian market.',
    highlights: ['Engineering partners'],
    projects: [],
    sortOrder: 12,
  },
]

/** Export client slugs per presence (static detail fallback) */
export const STATIC_PRESENCE_CLIENT_SLUGS = {
  'saudi-arabia': ['al-bahr-saudi'],
  uae: ['quality-intl-uae', 'ocean-oilfield-uae', 'hatco-uae', 'acs-flow-dubai'],
  kuwait: ['az-trading-kuwait'],
  qatar: ['qatar-projects'],
  ghana: ['tomorrows-world-ghana'],
  nigeria: ['sahara-nigeria', 'star-best-nigeria'],
  egypt: ['iffco-egypt'],
  greece: ['huber-greece'],
  indonesia: ['cv-mediterania', 'global-mandira', 'berkata-karunia'],
  bangladesh: ['nde-bangladesh', 'khan-brothers'],
  iran: ['pars-sazokar-iran'],
  usa: ['green-engineered-us'],
}
